---
application:
  name: "pokecard-price-checker-for-discord"
  project: "poke-price-checker bot"
  organization: "QoveryCommunity"
  dockerfile: Dockerfile
routers:
- name: "main-pokecard-price-checker-for-discord"
  routes:
  - application_name: "pokecard-price-checker-for-discord"
    paths:
    - "/*"
